[package]
name = "secrets_validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
quote = "1.0"
proc-macro2 = "1.0"


[lib]
proc-macro = true
